# Naive Bayes Classifier - Gaussian - Iris Flower dataset


- You can find all the machine learning practice notebooks at [my GitHub page](https://github.com/elakiricoder)

### Imports

In [109]:
import pandas as pd
import numpy as np
import csv
import random

### Load the Data

In [110]:
df = pd.read_csv("IRIS.csv")

In [111]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### Split the Data

In [112]:
from sklearn.model_selection import train_test_split

In [113]:
X = df.drop(['species'], axis=1)
y = df['species']

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

### Create the model and Predict

In [115]:
from sklearn.naive_bayes import GaussianNB

In [116]:
gnb = GaussianNB()

In [117]:
pred_nbc = gnb.fit(X_train, y_train).predict(X_test)

### Evaluate the model

In [118]:
from sklearn.metrics import classification_report,confusion_matrix

In [119]:
print(confusion_matrix(y_test,pred_nbc))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [120]:
print(classification_report(y_test,pred_nbc))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



### Test a Sample

In [127]:
test_index = 0
y_test_np = np.array(y_test)
print(f'Actual --> {y_test_np[test_index]}  --  Prediction --> {pred_nbc[test_index]}')

Actual --> Iris-versicolor  --  Prediction --> Iris-versicolor
